### ISSUE TITLE
JSON parsing failure when page title has double quotation marks

### ISSUE THREAD

**Issue by IanYates** [Microsoft/IEDiagnosticsAdapter#15]
I happen to have an old MSDN page open in an IE tab - https://support2.microsoft.com/default.aspx?scid=kb;EN-US;198893

Here's the relevant bit of JSON that is being downloaded from the proxy to the Chrome page which fails parsing
```
{
        "description": "iexplore.exe",
        "devtoolsFrontendUrl": "",
        "id": "73422A89-3378-4376-AF65-763FAC8BC1B1",
        "title": "Effects of Checking "UseNetworkNameforComputerName" in MSCS",
        "type": "page",
        "url": "https://support2.microsoft.com/default.aspx?scid=kb;EN-US;198893",
        "webSocketDebuggerUrl": "ws://localhost:9222/devtools/page/73422A89-3378-4376-AF65-763FAC8BC1B1"
    }
```

Can the proxy be made to escape those double quote characters, or just exclude them from the title altogether?

**Comment by danmosemsft** [comment]
This should be fixed by [pull request 6](https://github.com/Microsoft/IEDiagnosticsAdapter/pull/6) but we haven't built a release yet.

It will be a few days -- meantime let me know if this is blocking you? Or possibly you can sync and build for yourself if you have Visual Studio.

Thanks for the report..
